# Generated by Django 3.0.8 on 2020-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('Covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forminfo',
            name='id',
        ),
        migrations.AddField(
            model_name='forminfo',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
